services:
  - type: web
    name: nigeria-bece
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: MYSQL_ADDON_HOST
        sync: false
      - key: MYSQL_ADDON_USER
        sync: false
      - key: MYSQL_ADDON_PASSWORD
        sync: false
      - key: MYSQL_ADDON_DB
        sync: false
      - key: MYSQL_ADDON_PORT
        value: 3306
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false